### ISSUE TITLE
Needs new maintainer 

### ISSUE THREAD

**Issue by josh** [josh/rack-ssl#43]
I don't quite have the time to maintain this gem any longer.

Looking for someone to take this gem over. If multiple people want to do it thats fine.

## Whats expected

You can do whatever you'd like, but really, this library is **done**. Theres really no new features it should support. But it needs updates when rack updates or ensuring compatibility with new ruby versions. If you're looking to do something crazy different, probably just make a new project. Follow http://semver.org when making version changes.

## What would happen

* I'll give you gem publish access `gem owner rack-ssl --add your@email`
* I'll remove my gem publishing privileges
* Your fork will be made the new network root
* All PRs and Issues will be closed here

## Possible candidates

People who already contributed or had good ideas.

cc @chopmo @qrush @rkh @xaviershay @maccman @gbuesing @mattmmatt @halorgium

**Comment by chopmo** [comment]
@josh I don't mind taking over.

**Comment by josh** [comment]
Done. Its all yours.

Thanks @chopmo!
